### ISSUE TITLE
How to hide change view button from main menu

### ISSUE THREAD

**Issue by SudipGhosh822** [Mike-Aniki/Aniki-Remix#2]
![IMG_20240921_222429](https://github.com/user-attachments/assets/cfbbe352-29db-4aca-99a5-2abb55322bca)

Version 1.7.5
Please help me🫠

**Comment by Mike-Aniki** [comment]
You can't hide it, you have to delete it completely, so go to the theme code and delete all the lines concerning changeviewbutton. This will surely cause bugs/crashes.

**Comment by SudipGhosh822** [comment]
![5th](https://github.com/user-attachments/assets/c9878fd0-087c-4289-9bf6-e72061e1c38f)
![6th](https://github.com/user-attachments/assets/d7205a5b-4c17-45db-8ecf-b3b52c00e832)
![Screenshot_2024-10-02-01-19-00-86_2c9606bce337650a539aceea20c7df58](https://github.com/user-attachments/assets/926f1465-2fbf-4a09-95b2-256e403edf9b)

![4th](https://github.com/user-attachments/assets/ec5233e6-3131-4c53-9119-21d5da8eab2f)

![3rd](https://github.com/user-attachments/assets/46429c3c-8afa-4023-ace4-fc6d46286f4e)

![2nd](https://github.com/user-attachments/assets/5f26d137-e7e7-4fcb-b578-db2c5c9ae1cc)
![1st](https://github.com/user-attachments/assets/2ff174af-8607-4ea2-8d0f-6d1f191d8b6e)
![Screenshot_2024-10-02-01-19-16-81_2c9606bce337650a539aceea20c7df58](https://github.com/user-attachments/assets/0823f306-9df6-49b2-bfa2-091ef08006bc)


Can you help me in this why this is happening 🙃i love this theme so much i don't wanna change it🫠

**Comment by Mike-Aniki** [comment]
This problem does not come from the theme but from playnite itself, so there is nothing I can do. The problem is the same with the default playnite theme.
